apiVersion: v1
kind: Secret
metadata:
  name: inference-service-token
  labels:
    group: inference-service
  annotations:
    kubernetes.io/service-account.name: token-sync-sa
type: kubernetes.io/service-account-token